### ISSUE TITLE
Create build system

### ISSUE THREAD

**Issue by dinapappor** [autosbc/rpidashcam#3]
Since just distributing code is not _that_  user friendly we need to setup a build system where we setup the code, systemd units and such to make a finished image ready to be written and plugged into the Pi. 

Focus on making a possible update automatic, ie using A/B partitions which are read only and trigger update when newer version is available.

**Comment by dinapappor** [comment]
Maybe docker is a viable option to distribute updates? :thinking: 

Pro's:

* I can cross compile releases (It's going to be needed for at least pillow)
* Switching between versions should be easy _and_ fast.

Cons:
* It's docker
* Might be harder to setup interconnections between different docker containers (webui et al)
* Overhead?

**Comment by dinapappor** [comment]
Accessing camera from docker seems largely successful. But now failing with:

```
root@f0a291bb95de:/# python3 /usr/local/bin/dashcam.py 
Traceback (most recent call last):
  File "/usr/local/bin/dashcam.py", line 491, in <module>
    d = DashCam()
  File "/usr/local/bin/dashcam.py", line 321, in __init__
    self.__dashcam_data = DashCamData(
  File "/usr/local/bin/dashcam.py", line 97, in __init__
    self.__gps = gps(mode=WATCH_ENABLE | WATCH_NEWSTYLE)
  File "/usr/local/lib/python3.10/site-packages/gps/gps.py", line 197, in __init__
    gpscommon.__init__(self, host, port, verbose, reconnect)
  File "/usr/local/lib/python3.10/site-packages/gps/client.py", line 43, in __init__
    self.connect(self.host, self.port)
  File "/usr/local/lib/python3.10/site-packages/gps/client.py", line 69, in connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

This tells me gpsd cant be accessed from within docker container or that it listens to localhost

**Comment by dinapappor** [comment]
gps sorted by binding it to `172.17.0.1` and instructing gps module to connect to that ip.
Now facing outdated gps code :sad_trombone:

**Comment by dinapappor** [comment]
With copying a modified client.py for gps module to the resulting image I was able to record dashcam video from within the docker image using the following: `docker run --name "RANDOM_NAME"  -v /opt/vc:/opt/vc -v `/mnt/storage:/mnt/storage` --device /dev/vchiq --privileged --entrypoint "" -it 0d53fc988b6e /bin/bash` :tada:

**Comment by dinapappor** [comment]
Building the actual image that the docker etc runs on _should_ be able to be done with pi-gen or the likes.

**Comment by dinapappor** [comment]
Now working on using `python:3.10.4-slim-buster` as baseimage. Since the normal image was horribly big. At the moment I'm at ~370 MiB instead of ~700+ MiB.

**Comment by dinapappor** [comment]
Decided to mount `/etc/raspberrydashcam` into the container instead. This is to make it easier to access config file from webui.

As of writing this is what I use to start the container (to test and debug `dashcam.py`: 

`docker run --name "funnyimagename" -v /etc/raspberrydashcam:/etc/raspberrydashcam -v /opt/vc:/opt/vc -v /mnt/storage:/mnt/storage --device /dev/vchiq --privileged --entrypoint "" -it d4301f8beba6 /bin/bash`

**Comment by dinapappor** [comment]
The modifications I needed to do in order to allow camera to be accessed from docker container is adding

```
SUBSYSTEM=="vchiq",MODE="0666"
```
into `/etc/udev/rules.d/99-camera.rules`

Likewise for gps to be connectable from docker container I disabled IPv6 and modiefed `/lib/systemd/system/gpsd.socket` to look like:

```
[Unit]
Description=GPS (Global Positioning System) Daemon Sockets

[Socket]
ListenStream=/var/run/gpsd.sock
ListenStream=172.17.0.1:2947
SocketMode=0600

[Install]
WantedBy=sockets.target
```

This binds it to the `docker0 ` which should not make it accessible from other network devices.

**Comment by dinapappor** [comment]
Building it with `docker build -t rpidashcam:0.0.1a` I am now able to start the dashcam by executing `docker run -v /etc/raspberrydashcam:/etc/raspberrydashcam -v /opt/vc:/opt/vc -v /mnt/storage:/mnt/storage --device /dev/vchiq --privileged rpidashcam:0.0.1a`

**Comment by dinapappor** [comment]
For some reason the videos doesn't work when recording through docker :thinking: 

Preview _is_ working.

**Comment by dinapappor** [comment]
Seeing that preview _is_ working, this is probably a problem with ffmpeg. Upon inspection I could see that it missed some flags for `./configure` which the debian version of ffmpeg didn't have. Handcompiling with better flags should resolve this.

**Comment by dinapappor** [comment]
Upon inspection we get the following errors for files recorded in docker: `moov atom not found`. This means that ffmpeg was killed abruptly.

With testing where I manually killed the ffmpeg process running in the container the videos working. This points to the python scripts not handling signals properly.

**Comment by dinapappor** [comment]
With the latest commit in https://github.com/autosbc/rpidashcam/pull/17 it now writes the `moov` atom correctly when using `docker stop <container`>

**Comment by dinapappor** [comment]
Need to run dashcam docker container with `--rm` flag to be able to re-use container name.
